spring.application.name=backend
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.endpoint=${R2_ENDPOINT}
r2.bucket=${R2_BUCKET}
r2.public-url=${R2_PUBLIC_URL}
r2.region=${R2_REGION}

openai.api.key=${OPENAI_API_KEY}

# Multipart limits
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:5MB}


spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}


app.name=${APP_NAME:AI Tools Hub}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}

java.net.preferIPv4Stack=${JAVA_NET_PREFER_IPV4_STACK:true}

spring.data.redis.repositories.enabled=${SPRING_DATA_REDIS_REPOSITORIES_ENABLED:false}
logging.level.org.mongodb.driver=${LOGGING_LEVEL_ORG_MONGODB_DRIVER:ERROR}

rate.limit.enabled=${RATE_LIMIT_ENABLED:false}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:2000ms}

